# Above all, you must run config, then all the others

### update some field value of student
GET http://localhost:8222/api/v1/students/1/schoolId/2
Accept: application/json

### get a school list, listening port 8070 (school port, not gateway)
GET http://localhost:8070/api/v1/schools
Accept: application/json

### get some school with its student list
GET http://localhost:8222/api/v1/schools/with-students/1
Accept: application/json

### get a student list of some school
GET http://localhost:8222/api/v1/students/school/1
Accept: application/json

### get a school list
GET http://localhost:8222/api/v1/schools
Accept: application/json

### get a student list
GET http://localhost:8222/api/v1/students
Accept: application/json

### get a student by id
GET http://localhost:8222/api/v1/students/1
Accept: application/json

### get a school by id
GET http://localhost:8222/api/v1/schools/1
Accept: application/json

### add a new student
POST http://localhost:8222/api/v1/students
Content-Type: application/json

{
  "email": "Some Mail",
  "firstname": "Some Name",
  "lastname": "Some Surname",
  "schoolId": 1
}

### add a new school
POST http://localhost:8222/api/v1/schools
Content-Type: application/json

{
  "name": "Some Name",
  "email": "Some Mail"
}