eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8050
spring:
  application:
    name: email-sender
  mail:
    host: smtp.gmail.com
    username: thekhachik2021@gmail.com
    password: tjbymsqalynymbcm
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  tracing:
    sampling:
      probability: 1.0
      # Probability of sampling data for tracing (1.0 means 100%).
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
