eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/students/**
        - id: schools
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/schools/**
      # Here you can configure routes to route requests to different services.
      # There are two routes: students and schools, which route requests to the appropriate services on ports 8090 and 8070.
      # For example: GET http://localhost:8222/api/v1/schools -> GET http://localhost:8070/api/v1/schools
management:
  tracing:
    sampling:
      probability: 1.0

