eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/students/**
        - id: schools
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/schools/**
        - id: email-sender
          uri: http://localhost:8050
          predicates:
            - Path=/api/v1/mail/**
      # Here you can configure routes to route requests to different services.
      # There are two routes: students and schools, which route requests to the appropriate services on ports 8090 and 8070.
      # For example: GET http://localhost:8222/api/v1/schools -> GET http://localhost:8070/api/v1/schools
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  tracing:
    sampling:
      probability: 1.0
      # Probability of sampling data for tracing (1.0 means 100%).
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

